MODULE_STATUS = [
    {
        "module": "project_tracker",
        "completion_pct": 85,
        "algorithms": ["Pseudo-LSTM", "DecisionTree", "RandomForest"],
        "metric_name": "f1",
        "metric_value": 0.9976,
        "target": "> 0.70",
        "blockers": "Needs real 5+ year Nigerian weather/project data and true LSTM training.",
    },
    {
        "module": "procurement_assistant",
        "completion_pct": 75,
        "algorithms": ["Supplier scoring rules", "ARIMA(3,1,2)"],
        "metric_name": "mape",
        "metric_value": 0.0033,
        "target": "Procurement cycle 14->7 days",
        "blockers": "Runtime still uses mock supplier pricing; live supplier integrations pending.",
    },
    {
        "module": "safety_dashboard",
        "completion_pct": 70,
        "algorithms": ["Keyword hazard detection", "TF-IDF + LogisticRegression"],
        "metric_name": "recall",
        "metric_value": 1.0,
        "target": "> 0.80",
        "blockers": "Full RAG/LLM inference with real site logs and standards not yet integrated.",
    },
    {
        "module": "document_analyzer",
        "completion_pct": 70,
        "algorithms": ["Clause rule extraction", "TF-IDF + LogisticRegression"],
        "metric_name": "accuracy",
        "metric_value": 1.0,
        "target": "> 0.85",
        "blockers": "No fine-tuned Llama/Mistral model yet on Nigerian legal corpora.",
    },
    {
        "module": "cost_estimator",
        "completion_pct": 85,
        "algorithms": ["QTO baseline", "RandomForest ensemble"],
        "metric_name": "mape",
        "metric_value": 0.0626,
        "target": "< 0.10",
        "blockers": "Needs production historical cost data and supplier trend integration.",
    },
    {
        "module": "workforce_scheduler",
        "completion_pct": 65,
        "algorithms": ["Greedy workforce allocation"],
        "metric_name": "idle_rate",
        "metric_value": None,
        "target": "Reduce idle time",
        "blockers": "Linear programming/genetic optimization not yet implemented.",
    },
    {
        "module": "maintenance_predictor",
        "completion_pct": 65,
        "algorithms": ["Heuristic risk scoring", "ARIMA proxy"],
        "metric_name": "mape_proxy",
        "metric_value": 0.0055,
        "target": "Predictive maintenance scheduling KPI",
        "blockers": "Uses proxy signal; equipment telemetry and failure labels pending.",
    },
    {
        "module": "progress_visualizer",
        "completion_pct": 55,
        "algorithms": ["Deviation threshold logic"],
        "metric_name": "deviation_threshold_pct",
        "metric_value": 15.0,
        "target": "> 15% deviation alerts",
        "blockers": "YOLO/EfficientDet computer-vision pipeline not yet connected.",
    },
    {
        "module": "tender_analyzer",
        "completion_pct": 65,
        "algorithms": ["Risk phrase NLP mapping"],
        "metric_name": "risk_extraction_quality",
        "metric_value": None,
        "target": "Actionable risk extraction and summarization",
        "blockers": "No BERT/RoBERTa training or real tender corpus ingestion yet.",
    },
    {
        "module": "integration_suite",
        "completion_pct": 90,
        "algorithms": ["API key auth", "JWT RBAC"],
        "metric_name": "route_availability",
        "metric_value": 1.0,
        "target": "Stable auth and routing",
        "blockers": "Rate limiting and centralized audit logs still pending.",
    },
]


ENDPOINT_CATALOG = [
    {"method": "GET", "path": "/api/v1/health", "module": "health"},
    {"method": "POST", "path": "/api/v1/integration/token", "module": "integration_suite"},
    {"method": "POST", "path": "/api/v1/integration/refresh", "module": "integration_suite"},
    {"method": "GET", "path": "/api/v1/integration/module-status", "module": "integration_suite"},
    {"method": "GET", "path": "/api/v1/integration/endpoints", "module": "integration_suite"},
    {"method": "POST", "path": "/api/v1/project-tracker/predict-delay", "module": "project_tracker"},
    {"method": "POST", "path": "/api/v1/procurement/supplier-intelligence", "module": "procurement_assistant"},
    {"method": "POST", "path": "/api/v1/safety/analyze-log", "module": "safety_dashboard"},
    {"method": "POST", "path": "/api/v1/document-analyzer/review", "module": "document_analyzer"},
    {"method": "POST", "path": "/api/v1/cost-estimator/estimate", "module": "cost_estimator"},
    {"method": "POST", "path": "/api/v1/workforce/optimize", "module": "workforce_scheduler"},
    {"method": "POST", "path": "/api/v1/maintenance/predict", "module": "maintenance_predictor"},
    {"method": "POST", "path": "/api/v1/progress-visualizer/analyze", "module": "progress_visualizer"},
    {"method": "POST", "path": "/api/v1/tender-analyzer/analyze", "module": "tender_analyzer"},
]
